[package]
name = "saltpack"
version = "0.1.0"
authors = ["Phaiax <phaiax-saltpack@invisibletower.de>"]

[dependencies]
serde = "*"
serde_json = "*"
serde_macros = "*"
geometry = { path = "crates/ramp" }
ramp = "*"
byteorder = "0.4"